query myCompany {
  myCompany {
    id
    credits
    name
    contact {
      id
      name
      email
    }
    employees(where: { deleted: false }) {
      id
      name
      email
      deleted
    }
    interviews(where: { deleted: false }) {
      id
    }
  }
}
