# import * from './schema.graphql'

query myResultsConnection(
  $where: ResultWhereInput
  $orderBy: ResultOrderByInput
) {
  myResultsConnection(where: $where, orderBy: $orderBy) {
    aggregate {
      count
    }
  }
}
